name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on: codebuild-test-github-cmh-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "This is a test for test-github-cmh project in CodeBuild CMH!"
